apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    app: {{ .Values.project.name }}
    version: {{ .Values.project.version }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - name: api
    port: 8000
  - name: metrics
    port: 8112
  selector:
    app: {{ .Values.project.name }}
    version: {{ .Values.project.version }}
