image:
  name: "giantswarm/etcd-backup-operator"
  tag: "[[ .Version ]]"
Installation:
  V1:
    Registry:
      Domain: quay.io
pod:
  user:
    id: 1000
  group:
    id: 1000
project:
  name: "etcd-backup-operator"
  version: "[[ .Version ]]"
